# Generated by Django 2.2.6 on 2020-02-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeleteActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, editable=False, max_length=250, null=True, unique=True)),
                ('email', models.EmailField(max_length=250)),
                ('expire_on', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activation Code for Account Delete',
                'verbose_name_plural': 'Activation Codes for Account Delete',
                'ordering': ('-created',),
            },
        ),
    ]
