# Generated by Django 2.2.6 on 2020-02-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
